### PR TITLE
Frontend hmda-help

### LINKED ISSUE #616: Include hmda-help in hmda-frontend
Although the [hmda-help app](https://github.com/cfpb/hmda-help) has somewhat of a different audience than the rest of the apps (and won't live in the header), it's still probably worthwhile for code reuse and dep management to include it in this repo

### PR DESCRIPTION
**Pull request by wpears**
Closes #616 

@meissadia would you be able to fix the cypress tests?

Didn't do a ton of retrofitting, just pointing to the common loading icon and tuning some css

### CODE REVIEW

**Comment by meissadia** [comment]
@wpears Working on Cypress tests.  Looks like there's a glitch in the Note History api which is causing `hmda-help/institution.spec.js` to fail.

**Comment by meissadia** [comment]
I've made some progress towards getting the HDMA Help tests running against the local Platform, with `/v2/filing` and `/v2/admin` APIs working well.  But I can't get the `/v2/public` api working by proxying from the React app (/v2/public => localhost:9092), thus I'm unable to read the Note History data in the app.

[Proxy Configuration](https://github.com/cfpb/hmda-frontend/blob/frontend-hh/src/setupProxy.js)

Starting local APIs
`JAVA_OPTS="-Xmx8096m" sbt "project hmda-platform" "run"` # Ports 8080, 8081
`JAVA_OPTS="-Xmx8096m" sbt "project institution-api" "run"` # Port 9092

If I hit the endpoint from a browser or Postman, I get the expected response, but not from inside the React app.

**Comment by meissadia** [comment]
@wpears I can't get HMDA Help to play well with the Institutions API on TravisCI which leads to Note History related tests failing.  I'm able to get it working locally but encounter a `Connection Reset` error on CI. 

HH-FE-Proxy-Error

Checking the listeners on CI everything looks as expected, with the Institutions API listener matching the setup used by Filing/Admin, which both work well on CI.

Travis-INST-PORT

I've tried running the Institutions API on different ports (3010, 7000, 8282) but that hasn't helped.  [Here is the video](https://dashboard.cypress.io/projects/uk89dv/runs/8/specs/f82c7393-f9a1-4b4b-8331-daa62dc91d48/video?utm_source=Dashboard&utm_medium=Share+URL&utm_campaign=Video) of the test run where we can see that the Note History shows "Unable to fetch data" after failing to reach the Institutions API but it doesn't provide any additional info on why the failure occurred.  

For now I'm skipping the Note History related tests, which gets the test suite passing again, until I can figure out a workaround to the bug on CI.  

Before we merge this I'll need to check with the DevOps team on what changes need to be made at the network layer to allow the Frontend app to receive the traffic at `ffiec.cfpb.gov/hmda-help` instead of it being sent to the separate HMDA Help deployment. 

If you have any bandwidth to double check the setup on this branch, it'd be great to have a second set of eyes, in case I'm missing something obvious.

Helpful links:
- [setupProxy](https://github.com/cfpb/hmda-frontend/blob/f38e180e437078f7b9c62c704b136b8fff3c3183/src/setupProxy.js) - Configuration of proxies to Filing/Admin/Institutions
- [Travis config](https://github.com/cfpb/hmda-frontend/blob/f38e180e437078f7b9c62c704b136b8fff3c3183/.travis.yml)
  - Sets [port for Institutions API](https://github.com/cfpb/hmda-frontend/blob/f38e180e437078f7b9c62c704b136b8fff3c3183/.travis.yml#L25)
  - [Starts and waits for Institutions API to load](https://github.com/cfpb/hmda-frontend/blob/f38e180e437078f7b9c62c704b136b8fff3c3183/.travis.yml#L41-L42)

**Comment by wpears** [comment]
Nothing obvious that I can tell, pretty puzzling result. My guess is a timing issue around the institutions-api not actually being set up? Or perhaps some subtle step that's missing in establishing getting the institutions-api to return data properly.

**Comment by meissadia** [comment]
Thanks for checking.

**Comment by meissadia** [comment]
Working with Ops to test rerouting of traffic in `dev-default`.

**Comment by meissadia** [comment]
Deployment to `dev-default` was successful.

Some supporting services are not deployed on `dev-beta` but routing to the integrated HMDA Help app was also successful.

Cypress tests (minus the Note History related checks) all pass. 

Merging.

**Pull request merged**
