### PR TITLE
Filter variable for maps and graphs

### PR DESCRIPTION
**Pull request by wpears**
## Changes

- Adds filter variable and filter value selectors to the maps and graphs view of data-browser.
- Updates legend logic to automatically calculate the appropriate legend based on the displayed data
- Bit of directory renaming to clear up databrowser pieces

### CODE REVIEW

**Comment by meissadia** [comment]
Bug #1 - App crash from what seems to be missing option data in the `buildTable` method.
- Step 1: select State
- Step 2: select Action Taken
- Step 3: select first option
- Step 4: select Loan Type
- Step 5: select first option
- Click on a State to bring up the summary table
- Step 2: change Action Taken to Loan Type
- Step 3: select first option
- Step 4: select Action Taken
- Step 5: select first option
- Observe error

Screen Shot 2020-09-03 at 2 59 54 PM
Maybe there's a gap in the generated data files?  In this scenario `currData` does not data for the key `loanType` which results in `currVarData` being `undefined`. 

Screen Shot 2020-09-03 at 3 03 35 PM

**Comment by meissadia** [comment]
Bug #2 - Geography color in the choropleth does not correctly match the legend when filtering by two variables

[Example #1](http://localhost:3000/data-browser/maps-graphs/2018?geography=state&variable=actionTaken&value=1&filter=loanType&filtervalue=1&feature=39): Action Taken = 1 and Loan Type = 1
- Ohio (24.73) appears to fall into the 12 - 23.99 bucket
- Colorado (40.49) appears to fall into the 24 - 35.99 bucket
  Screen Shot 2020-09-03 at 2 02 26 PM
  Screen Shot 2020-09-03 at 3 10 02 PM

[Example #2](http://localhost:3000/data-browser/maps-graphs/2018?geography=state&variable=loanType&value=2&filter=lienStatus&filtervalue=2): Loan Type = 2 and Lien Status = 2
- Every state other than Michigan appears to fall in the `0 - 0.49` bucket (Texas - 6.96, Georgia - 10.45)
- Michigan (0) should be in the `0 - 0.49` but appears to fall below the threshold
  Screen Shot 2020-09-03 at 2 03 33 PM

**Review by meissadia — CHANGES_REQUESTED** [review]
Couple of bug reports in the comments.

**Comment by wpears** [comment]
@meissadia those two bugs should be addressed in the latest commits (I actually realized I forgot to fix bug number two before opening the PR as I drove up into the mountains, then promptly forgot!)

**Comment by meissadia** [comment]
@wpears Fixes for [Bug #1](https://github.com/cfpb/hmda-frontend/pull/640#issuecomment-686764085) and [Bug #2](https://github.com/cfpb/hmda-frontend/pull/640#issuecomment-686771232) look good 👍🏽 

I do notice that the map's zoom controls aren't rendering.  I don't see any failures in the `Network` tab for fetching the icons.  I also don't see anything in your latest commits that modify the zoom controls.  Is this replicable on your end?  
Zoom-controls

**Comment by wpears** [comment]
I can't reproduce this, does it happen in incognito? Across multiple browsers?

**Comment by meissadia** [comment]
> I can't reproduce this, does it happen in incognito? Across multiple browsers?

Yes it happens in an incognito browser.  Happens in Chrome and Safari, unable to verify on IE.

**Comment by meissadia** [comment]
Map zoom controls is just an issue on my local instance:
- Tested via Docker and everything runs correctly
- Trying to deploy to dev-default but hitting errors

Pending validations:
- Deployment is successful
- Download of data is successful
- Downloaded data is correct

**Review by meissadia — APPROVED** [review]
Was able to successfully deploy as well as download the csv. 👍🏽 :shipit:

**Pull request merged**
