### PR TITLE
[Beta] Add banner for preview of new LARFT

### LINKED ISSUE #1360: [Beta] Add banner for preview of new LARFT

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1360

Screen Shot 2022-02-24 at 12 06 13 PM

### CODE REVIEW

**Comment by meissadia** [comment]
@chynnakeys @lchen-2101 Please review the language for this banner.

**Review by lchen-2101 — COMMENTED** [review]
The long link throws me a bit, maybe we can do something like: `You can preview the new LAR Formatting tool on the HMDA Beta Platform here.` with the link just on the `here`. I'm guessing the banner system doesn't have a text before link, and text after link type of messaging capability yet?

**Comment by meissadia** [comment]
@chynnakeys No, we don't have that level of control, the link is always the last thing.  
 
 How about this?
Screen Shot 2022-02-26 at 12 27 48 PM

**Comment by chynnakeys** [comment]
I would change the last sentence to "Updates will be made to this tool iteratively, and the latest version is available now on the HMDA Beta"

**Comment by meissadia** [comment]
@chynnakeys
Screen Shot 2022-03-01 at 2 15 30 PM

**Pull request merged**
