### PR TITLE
Frontend Security Updates

### LINKED ISSUE #1186: Cypress test pod security checkup
- Identify and resolve CVEs
- Update Cypress
- Push and merge Dockerfile updates
- Build and deploy updated pod

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1186 

## Changes
- Updated Dependencies
  - Fixes 31 Moderate, 18 High, 2 Critical
  - 1 remaining High CVE ([ansi-html](https://www.npmjs.com/advisories/1002522))
- Updated Cypress tests for compatibility with upgraded API
## Testing - Successful
- Local testing looks good
- I've done a test deployment to Production during off-hours and run the full Cypress suite to verify all integrations remain in good working order.

### CODE REVIEW

**Comment by lchen-2101** [comment]
why are binaries of the dependencies in the repo? is it to speed up the build process?

**Comment by meissadia** [comment]
> why are binaries of the dependencies in the repo? is it to speed up the build process?

I feel like this was part of the requirements for a now defunct build process that wasn't allowed to download dependencies.  Or maybe it was an addition to allow for offline development once the dev has the repo?

**Review by lchen-2101 — APPROVED** [review]
LGTM

**Comment by lchen-2101** [comment]
todo: need to look into whether we can remove the binaries from the repo.

**Pull request merged**
