### PR TITLE
Change Log

### LINKED ISSUE #648: Publications Change Log
New datasets and products are being released and prior datasets are receiving material updates. These updates, changes, and new products need to be communicated to end users. Creating a section that contains information similar to patch notes would provide us an area to publish metadata regarding updates.

## Current behavior
No updates are supplied to data users regarding changes to datasets or data products.

## Expected behavior
Users are made aware of changes made to datasets and data products so they can assess impacts to their work.

### LINKED ISSUE #766: Data publication changes page updates
- [x] Change the change log order from Correction, Release, Update to Release, Update, Correction 

- [x] HMDA Tools instead of HMDA Apps

- [x] Would we be able to call Datasets "National Datasets" to distinguish between mLAR?

- [x] Change HDMA to HMDA in description

- [x] Remove ordinal indicator from dates (June 24 as opposed to 24th)

### PR DESCRIPTION
**Pull request by meissadia**
Closes #648 
Closes #766 

- [x] Address feedback from Friday's demo
- [x] Integrate cleared language

Screen Shot 2020-12-15 at 12 42 36 PM

### CODE REVIEW

**Review by wpears — CHANGES_REQUESTED** [review]
This looks really cool, nice work!

Could you add a style to `.filter-bar .pill.selected` items with `text-decoration: underline` or some alternate indication of the currently selected items that isn't wholly color-based?

**Review by wpears — CHANGES_REQUESTED** [review]
Looks great overall! The one question about useRemoteJSON fetching and also this isn't working in ie11. I'd recommend bumping `react-app-polyfill` to 2.0.0 as a first step in getting it working there.

**Comment by meissadia** [comment]
@wpears Thanks for kicking off the cross browser testing.  I'm waiting for a password reset to be able to access IE, then I'll dig into those issues.

Added some improvements to `useRemoteJSON`.

**Comment by wpears** [comment]
Was able to get the polyfills working correctly with a small change.

Something else to look at is the icons are misaligned in ie11:
Screen Shot 2020-11-23 at 5 51 21 PM

**Comment by meissadia** [comment]
@wpears Thanks so much for fixing the Polyfills!  

- Fixed pill icon alignment on IE
- Fixed squished icon for Filtered Results
- Validated functionality

Deployed on dev-beta.

Screen Shot 2020-11-24 at 12 57 41 PM

**Review by wpears — APPROVED** [review]
🥳 sweeeeeeeeeeeet! Nice job! Merge when ready

**Comment by kgudel** [comment]
LGTM

**Pull request merged**
