### PR TITLE
Rtk query update

### LINKED ISSUE #1528: [Graphs] RTK Query for simplified data fetching
Utilize RTKQ to reduce the amount of boilerplate code needed to handle data pulled in from the Graphs API and stored in Redux.
 
https://redux-toolkit.js.org/tutorials/rtk-query

### PR DESCRIPTION
**Pull request by lchen-2101**
closes #1528

### CODE REVIEW

**Review by meissadia — APPROVED** [review]
Awesome! Really simplifies things, thanks for this.  
 
 I'll wait until @Michaeldremy has a chance to review and ask questions before we merge.

**Review by Michaeldremy — CHANGES_REQUESTED** [review]
Code looks great! I agree with Meissa it really simplifies everything. I did notice a visual bug that I am seeing. See my thought below.

I pulled down the branch locally and was doing manual testing and I found a potential issue.

Observations:

While viewing the graphs on the production website and cycling through the graphs, Highcharts will smoothly transition from one graph to another.

Issue:

When you select a different graph besides the initial one that is pre-loaded it starts to fill with the old graph information for a brief second then it loads the graph you selected. This is causing a **jolt** like effect.

After viewing multiple graphs and then traversing back it transitions smoothly again (since we are caching the request/data of the already viewed graphs)

**Comment by lchen-2101** [comment]
> Member

We've jumped on a call and saw the both branches behave the same way while running locally.

**Review by Michaeldremy — APPROVED** [review]
LGTM

**Pull request merged**
