### PR TITLE
Hover percent

### LINKED ISSUE #573: Add originations per thousand to geography to hover popup
Assists with #566

### PR DESCRIPTION
**Pull request by wpears**
Closes #573

### CODE REVIEW

**Comment by meissadia** [comment]
<strong> Per 1000 hover showing as "0" for all states/counties despite the choropleth indicating they should vary.</strong>

per1000-all-zero

Example URLs:

http://localhost:3000/data-browser/maps-graphs/2018?geography=state&variable=ethnicity&value=Not%20Hispanic%20or%20Latino&feature=08

http://localhost:3000/data-browser/maps-graphs/2018?geography=state&variable=ethnicity&value=Hispanic%20or%20Latino&feature=08

http://localhost:3000/data-browser/maps-graphs/2018?geography=state&variable=ethnicity&value=Ethnicity%20Not%20Available&feature=08

http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=ethnicity&value=Hispanic%20or%20Latino

http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=ethnicity&value=Ethnicity%20Not%20Available

http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=race&value=American%20Indian%20or%20Alaska%20Native

http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=race&value=Black%20or%20African%20American

**Comment by meissadia** [comment]
<strong>When quickly highlighting different geographies, there is a trailing highlight.  Don't think it's a problem, as the UI continues to respond to new selections by quickly updating the summary table. </strong>

trailing-highlighter

**Comment by meissadia** [comment]
<strong>Rapidly clicking around can sometimes lead to a page crash.</strong>

quick-click-error

**Comment by wpears** [comment]
@meissadia The crashing and 0-value percents have been fixed in the above commits

**Pull request merged**
