### PR TITLE
[Filing] Stalled uploads

### LINKED ISSUE #1115: Filing: How to handle long uploads
- User was seeing that a file was uploaded, but not yet processed, three days after the initial upload. 
- Option: When polling for upload progress, if it's been over 24hrs, simply show error and request that user re-upload their file.
- Consider: This *may* not be relevant once we leverage the websockets version of the progress bar.

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1115 

## Changes
- Display the `stalled upload` status if an Upload is not processed after 5hrs.
- Improve accuracy of `SubmissionNav` upload status indicator.
- Display `Refile` button, prompting user to re-upload, when `stalled`.

## Manual local testing
1. Paste the following snippet in `src/filing/institutions/Institution.jsx` at line 20
```
   submission = {
    id: {
      lei: 'FRONTENDTESTBANK9999',
      period: { year: 2019, quarter: null },
      sequenceNumber: 1005,
    },
    status: {
      code: 3,
      message: 'Your file has been uploaded.',
      description: 'Your data is ready to be analyzed.',
    },
    start: 1640650476515,
    end: 0,
    fileName: '2019-FRONTENDTESTBANK9999.txt',
    receipt: '',
    signerUsername: null,
    qualityVerified: false,
    macroVerified: false,
    qualityExists: false,
     macroExists: false,
    isStalled: true,
   }
```
2. Visit http://localhost:3000/filing/2019/institutions
3. Observe `After` state from the screenshots below

## Screenshots

Name | Description | Screenshot
---|---|---
Before | <ul><li>Submission nav is not updated</li><li>Messaging is self-contradictory (file is uploaded / View upload progress)</li></ul> |  before
After | <ul><li>Submission nav shows error </li><li> All messaging indicates user needs to re-upload their file</li></ul> | Screen Shot 2022-01-13 at 12 52 22 PM

### CODE REVIEW

**Comment by meissadia** [comment]
@lchen-2101 This has been updated with the 5hr timeout discussed during Standup.

**Review by lchen-2101 — COMMENTED** [review]
I wonder if we should just store the `isStalled` information when the app first loads up, so the calculation doesn't need to be done in every component that might display this information.

**Comment by meissadia** [comment]
- I've moved stalled upload status determination into Redux to have this flag centralized

**Review by lchen-2101 — APPROVED** [review]
LGTM

**Pull request merged**
