### PR TITLE
Cache S3 last updated dates

### LINKED ISSUE #1260: Cache values fetched with useS3LastUpdated

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1260 

- This explores the use of Redux Toolkit (RTK) via a separate, very localized, store.
- Long-term, we'll want to move to a single app-wide store. This will be explored in #1269 though not likely going to be released until after 2021 Annual.

### CODE REVIEW

**Comment by PatrickGoRaft** [comment]
@meissadia  this branch has merge conflicts

**Comment by meissadia** [comment]
@PatrickGoRaft Conflicts resolved.

**Comment by meissadia** [comment]
@PatrickGoRaft Conflicts resolved again.

**Review by PatrickGoRaft — APPROVED** [review]
LGTM.

**Pull request merged**
