### PR TITLE
Add 2019 to maps and graphs

### LINKED ISSUE #637: Add 2019 Data to maps and graphs

### PR DESCRIPTION
**Pull request by wpears**
Depends on https://github.com/cfpb/hmda-frontend/pull/640
Closes #637 

Adds the ability to switch between 2018 and 2019 for the maps/graphs view. Data has been generated and added to s3.

### CODE REVIEW

**Comment by meissadia** [comment]
Issue #1 

New Mexico tooltip shows 0, choropleth shows it as >= 10 
http://localhost:3000/data-browser/maps-graphs/2019?geography=state&variable=loanType&value=1&filter=actionTaken&filtervalue=6

Screen Shot 2020-10-01 at 12 57 09 PM


Same issue for simpler selection criteria
Screen Shot 2020-10-01 at 12 59 05 PM

http://localhost:3001/data-browser/maps-graphs/2019?geography=state&variable=loanType&value=1&feature=48

**Comment by meissadia** [comment]
Issue #2 - Summary stats don't update when switching years.

Both of these links display the same Summary table despite being for different years.
http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=loanType&value=1&feature=49025
http://localhost:3000/data-browser/maps-graphs/2019?geography=county&variable=loanType&value=1&feature=04005


Screen Shot 2020-10-01 at 1 06 59 PM

If I have a second filter variable selected, the Summary tables seem to be updated correctly.
http://localhost:3000/data-browser/maps-graphs/2018?geography=county&variable=loanType&value=1&filter=actionTaken&filtervalue=1&feature=49025


http://localhost:3000/data-browser/maps-graphs/2019?geography=county&variable=loanType&value=1&filter=actionTaken&filtervalue=1&feature=49025

**Review by meissadia — CHANGES_REQUESTED** [review]
Couple of issues, left comments.

**Comment by wpears** [comment]
@meissadia Both those issues should now be addressed

**Review by meissadia — APPROVED** [review]
@wpears The updated app looks great, thanks for the fixes! 👍🏽

**Pull request merged**
