### PR TITLE
Quarterly Filing

### LINKED ISSUE #77: Quarterly Filing
When quarterly filing is open, only Institutions flagged as `quarterlyFiler` should see the option to submit a filing for a quarter.

`/filing/institutions/<lei>/year/<year>` should now return a new boolean key `quarterlyFiler`. This is covered in this PR in the backend https://github.com/cfpb/hmda-platform/pull/3246/files

## Current behavior
Quarterly filing is not implemented.

## Expected behavior
Quarterly filers should be able to 
- submit quarterly filings for an open filing quarter
- view all previous annual and quarterly filings
- filter the displayed institutions to only include those that
  - have previous filings for the selected year/quarter
  - are eligible to submit filings for the selected year/quarter

## Notes
Original issue: https://github.com/cfpb/hmda-platform-ui/issues/1297
Prototype: https://github.com/cfpb/hmda-platform-ui/pull/1320

### LINKED ISSUE #273: Extract FILING_DEADLINE to Environment Variable
## Current behavior

Changing the FILING_DEADLINE value to trigger the "filing deadline has  passed"  warning requires a code change to implement.  

## Expected behavior

Changing the filing deadline date value should be configurable via an environment variable.

### LINKED ISSUE #294: Merge Quarterly Filing
Quarterly Filing is finally ready to be merged!

Successfully tested deployment to `dev-default` yesterday. 

As discussed during standup, we will merge to `master`, verify again in `dev-default`, and then in `prod-beta`.  

PR https://github.com/cfpb/hmda-frontend/pull/136

### PR DESCRIPTION
**Pull request by meissadia**
Closes #77 
Closes #273 
Closes #294

## Changes
- Enables submission of QFilings for QFilers
- Moves open/closing dates of QPeriods to env config
- Prevents creation of Filings for passed QPeriods
- Prevents new submissions for passed QPeriods
- Updates Institution banner messaging for QPeriods
- Displays lists of NonQFilers and Filers without Filings for past Qs

## Testing
All 2020 quarters are Open for submission in the `dev-default` filing API.

I used the hmda-help repo to create test institutions for 2020 but you can use the existing institutions below for testing.

Test Institutions:
  - B90YWS6AFX2LGWOXJ1MD [ 2020 QFiler with Filings for all Qs, submissions for Q1/Q3]
  - MEISSADIATESTBANK001 [2020 NonQFiler]

I'd be glad to demo anything that you need to see. 
Can also provide test files for submissions. 

## Notes
- Modified *.test.js files were carried over from the previous repo and can be removed

### CODE REVIEW

**Comment by wpears** [comment]
@meissadia Re-reviewed this and I think we're (mostly) ready to go!

Really only one question and one styling suggestion:

Q: It appears that a user is able to upload a file to a quarter even when that quarter is not open (and the header says as much). Is this intentional? Seems to me we'd specifically want to prevent filing for future, unopened periods if we're calling them out as unopened. See below for appearance:
Screen Shot 2020-02-20 at 12 00 55 AM

Styling suggestion: I think the font colors in the drag n drop box should be reversed, since the message we're alerting is that the filing period is closed while the filing upload status is just informational.
Screen Shot 2020-02-19 at 11 57 18 PM

**Comment by meissadia** [comment]
@wpears Sorry, you had previously called out that we should hide the `Upload` button for closed quarters and I whiffed on that.   Added logic to achieve this, as well as hiding the refile button. 

I did not update the Submission view to account for future quarters under the assumption that if we prevent the creation of Submissions outside of the Filing Period's window, users would not encounter a scenario where they would be presented with one-click access into the Submission view, unless it was an open Period or a past Period.  

Also updated the styles for the disabled dropzone.

# Hide Upload
Screen Shot 2020-02-20 at 10 11 29 AM

# Hide Refile 
I don't think this scenario should never occur.  Where it's a future Period but the user already has a Submission in progress.  

Screen Shot 2020-02-20 at 10 13 14 AM

# Styles for Disabled Dropzone
Screen Shot 2020-02-20 at 11 13 00 AM

**Comment by wpears** [comment]
👍 looks good!

**Comment by wpears** [comment]
:+1:

**Pull request merged**
